name: Build SRS
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-lates

        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Compile LaTeX document
              uses: dante-ev/latex-action@master
              with:
                  root_file: main.tex
				  working-directory: ./p1
